# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"addition": "00_core.ipynb"}

modules = ["arithmatic.py"]

doc_url = "https://muellerzr.github.io/docmentation_demo/"

git_url = "https://github.com/muellerzr/documentation-demo/tree/master/"

def custom_doc_links(name): return None
