# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['addition']

# Cell
def addition(
    a:int, # The first number to add
    b:(float,int), # The second number to add
) -> (float,int): # The sum of a and b
    "Adds two numbers together"
    return a+b